apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-apigw
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;

    load_module modules/ngx_http_js_module.so;
    load_module modules/ndk_http_module.so;
    load_module modules/ngx_http_lua_module.so;

    error_log  /var/log/nginx/error.log  notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-conf
  namespace: nginx-apigw
data:
  default.conf: |-
    server {
      #listen 8080 default_server;
      listen 8080;
      server_name api;

      location /api/ {
        api write=on;
        #allow 0.0.0.0;
        #deny all;
      }

      location /dashboard.html {
        root /usr/share/nginx/html;
      }
      access_log off;
    }
